#Zedja Custom Cards
!setname 0xe00 Prismiant
!setname 0xe01 Wiccanthrope
!setname 0xe02 Ashens
!setname 0xe03 Lavoisier
!setname 0x1e03 Lavoisier Arsenal
!setname 0x1e04 Build Rider
!setname 0x2e04 Build Driver
!setname 0xe05 Milacresy
